language: node

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - docker --version

script:
  - docker build -t spirogov/timecoder-ui:latest .

after_script:
  - docker images

before_deploy:
  - docker tag "spirogov/timecoder-ui:latest" "spirogov/timecoder-ui:${TRAVIS_TAG}"
  - docker images
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push "spirogov/timecoder-ui:${TRAVIS_TAG}"
  on:
    tags: true