language: node

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - docker --version

script:
  - docker build -t spirogov/timecoder-ui:latest .

after_script:
  - docker images

before_deploy:
  - docker images
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  - provider: script
    script: docker tag "$IMAGE_NAME:latest" "${IMAGE_NAME}:${TRAVIS_TAG}" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
    on:
     tags: true
  - provider: script
    script: docker push "$IMAGE_NAME:latest"
    on:
      branch: master
